tagging_system/config/routes.rb
Rails.application.routes.draw do
 root :to => 'marketing#index'

 get '/about-us' => 'marketing#about_us'
 get '/maths-curriculum' => 'marketing#curriculum'
 get '/online-maths-intervention' => 'marketing#how_it_works'
 get '/meet-the-tutors' => 'marketing#meet_the_tutors'
 get '/book-a-demo' => 'marketing#book_a_demo'
 get '/our-schools' => 'marketing#our_schools'
 get '/our-schools/rush-green-primary-school' => 'marketing#rush_green_primary_school'
 get '/our-schools/springfield-primary-school' => 'marketing#springfield_primary_school'
 get '/our-schools/somers-heath-primary-school' => 'marketing#somers_heath_primary_school'
 get '/our-schools/green-park-primary-school' => 'marketing#green_park_primary_school'
 get '/our-schools/copthorne-primary-school' => 'marketing#copthorne_primary_school'
 get '/pricing' => 'marketing#pricing'
 get '/careers' => 'marketing#careers'
 get '/login' => 'marketing#login'
end

tagging_system/app/controllers/marketing_controller.rb
class MarketingController < ApplicationController
	layout 'marketing'
end

tagging_system/app/views/layouts/marketing/_flash_messages.html.erb
<% if flash[:success] %>
	<div class="flash-message flash-success">
		<div class="container">
			<div class="row">
				<div class="flash-icon"><%= image_tag("marketing/success-tick-icon.png") %></div>
				<p><%= flash[:success].to_s %></p>
				<%= link_to image_tag("marketing/cross-for-banner-alert.png"), "#", class: "flash-message-close", remote: true %>
			</div>
		</div>
	</div>
<% end %>

<% if flash[:error] %>
	<div class="flash-message flash-error">
		<div class="container">
			<%= image_tag("marketing/error-message-icon.png", class: "flash-icon") %>
			<p><%= flash[:error].to_s %></p>
			<%= link_to image_tag("marketing/cross-for-banner-alert.png"), "#", class: "flash-message-close", remote: true %>
		</div>
	</div>
<% end %>

tagging_system/app/views/layouts/marketing/_footer.html.erb
<footer class="container-fluid">
	<section class="row links">
		<div class="col-md-4 col-sm-6 contacts">
			<a class="link-with-icon pin link-dark" href="https://goo.gl/maps/zPpzY4nZUuQ2" target='_blank'>Kensington Aldridge Academy<br>1 Silchester Road, London W10 6EX</a>
			<a class="link-with-icon email link-dark" href="mailto:hello@thirdspacelearning.com">hello@thirdspacelearning.com</a>
			<a class="link-with-icon phone link-dark" href="callto:02037710093">0203 771 0093</a>
		</div>
		<div class="col-md-4 col-sm-6 social">
			<a class="link-with-icon twitter link-dark" href="https://twitter.com/thirdspacetweet" target='_blank'>@ThirdSpaceTweet</a>
			<a class="link-with-icon youtube link-dark" href="https://www.youtube.com/c/ThirdSpaceLearningTuition" target='_blank'>YouTube Channel</a>
			<a class="link-with-icon linkedin link-dark" href="https://www.linkedin.com/company/third-space-learning" target='_blank'>Linkedin</a>
		</div>
		<div class="col-md-4 col-sm-6 secondary-links">
			<a href="<%= about_us_path %>" class="link-dark">About Us</a>
			<a href="<%= careers_path %>" class="link-dark">Careers</a>
			<a href="<%= asset_path('Third-Space-Learning-terms-and-conditions.pdf') %>" class="link-dark" target='_blank'>Terms & Conditions</a>
			<a href="<%= asset_path('Third-Space-Learning-privacy-policy.pdf') %>" class="link-dark" target='_blank'>Privacy Policy</a>
		</div>
		<!-- Compacticons by tatosXL - http://tatosxl.deviantart.com/art/Compacticons-479216575 - tatuera@gmail.com - http://creativecommons.org/licenses/by-sa/3.0/ -->
	</section>
	<section class="marketing-input container">
		<p class="tondo col-md-8">Like what you see? Keep up to date with teaching tips, <span class="yellow-highlight">free resources and special offers.</span></p>
		<div class="email-input col-md-4">
			<div class="input-group-wrapper">
				<%= form_for DataCapture.new, method: "post" do |f| %>
					<%= f.text_field :email, placeholder: "Your email address", class: "form-field" %>
					<%= f.submit "Enter", class: "btn-3 form-submit" %>
				<% end %>
			</div>
		</div>
	</section>
</footer>

tagging_system/app/views/layouts/marketing/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="topbar-wrap navbar-left">
          <a class="navbar-brand" href="<%= root_path -%>">
            <%= image_tag 'marketing/third-space-learning-logo.png' %>
          </a>
        </div>
      </div>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class='nav topbar navbar-nav collapse navbar-collapse'>
          <li>
            <a class="btn-login" href="<%= new_user_session_path %>">Log In</a>
          </li>
          <li>
          <a class="btn-2" href="<%= book_a_demo_path %>">Book a demo</a>
          </li>
          <li><%= link_to '0203 771 0093', 'callto:02037710095' %></li>
        </ul>
        <ul class="nav navbar-nav main-menu navbar-right">
          <li class='<%= set_current_item_by_controller_and_action({ controller: "marketing", action: 'book_a_demo'}) -%> book-a-demo-menu'><a href="<%= book_a_demo_path %>">Book a demo</a></li>
          <li class='<%= set_current_item_by_controller_and_action({ controller: "marketing", action: 'index'}) -%>'><a href="<%= root_path -%>">Home</a></li>
          <li class='<%= set_current_item_by_controller_and_action({ controller: "marketing", action: 'how_it_works'}) -%>'><a href="<%= online_maths_intervention_path %>">How it Works</a></li>
          <li class='<%= set_current_item_by_controller_and_action({ controller: "marketing", action: 'our_schools'}) -%>'><a href="<%= our_schools_path %>">Our Schools</a></li>
          <li class='<%= set_current_item_by_controller_and_action({ controller: "marketing", action: 'curriculum'}) -%>'><a href="<%= maths_curriculum_path -%>">Curriculum</a></li>
          <li class='<%= set_current_item_by_controller_and_action({ controller: "marketing", action: 'meet_the_tutors'}) -%>'><a href="<%= meet_the_tutors_path %>">Tutors</a></li>
          <li class='<%= set_current_item_by_controller_and_action({ controller: "marketing", action: 'pricing'}) -%>'><a href="<%= pricing_path %>">Pricing</a></li>
          <li class='<%= set_current_item_by_controller_and_action({ controller: "marketing", action: 'about_us'}) -%>'><a href="<%= about_us_path %>">About Us</a></li>
          <li class='<%= set_current_item_by_controller_and_action({ controller: "marketing", action: 'careers'}) -%>'><a href="<%= careers_path %>">Careers</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>